program: train.py
project: "GRACE_recoverability_hps"
name: "REDDIT_recoverability"
method: bayes
metric:
  goal: maximize
  name: F1Mi_mean
parameters:
  use_wandb:
    values: [ true ]
  dataset:
    values: ["Reddit"]
  method:
    values: ["recoverability"]
  Reddit.learning_rate:
    values: [1e-4, 5e-5, 1e-5, 5e-6, 1e-6]
  Reddit.num_hidden:
    values: [128, 256, 512]
  Reddit.num_layers:
    values: [2, 4]
  Reddit.kernel_lambda:
    values: [100, 10, 1, 0, 1e-2, 1e-3, 1e-4, 1e-5]
  Reddit.num_epochs:
    values: [100]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
