program: train.py
project: "GRACE_recoverability_hps"
name: "PPI_recoverability"
method: bayes
metric:
  goal: maximize
  name: F1Ma_mean
parameters:
  use_wandb:
    values: [true]
  dataset:
    values: ["PPI"]
  method:
    values: ["recoverability"]
  PPI.learning_rate:
    values: [1e-4, 5e-5, 1e-5, 5e-6, 1e-6]
  PPI.num_hidden:
    values: [128, 256, 512]
  PPI.num_layers:
    values: [2, 4]
  PPI.kernel_lambda:
    values: [100, 10, 1, 0, 1e-2, 1e-3, 1e-4, 1e-5]
  PPI.num_epochs:
    values: [ 100 ]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
