dataset: ~
method: ~
use_wandb: false
multi_gpu: false
wandb_project: GRACE_recoverability
exp_type: unsupervised
Cora:
  seed: 39788
  learning_rate: 0.00005
  num_hidden: 512
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 4
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 1
  num_data_splits: 1
  eval_method: GRACE
  use_half_precision: false
amazon_photos:
  seed: 39788
  learning_rate: 0.0001
  num_hidden: 512
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 0.01
  num_data_splits: 1
  eval_method: GRACE
  use_half_precision: false
PPI:
  seed: 39788
  learning_rate: 0.000001
  num_hidden: 512
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 0.00001
  num_data_splits: 1
  eval_method: DGI
  use_half_precision: false
CiteSeer:
  seed: 38108
  learning_rate: 0.00005
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  num_epochs: 200
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 1
  num_data_splits: 1
  eval_method: GRACE
  use_half_precision: false
PubMed:
  seed: 23344
  learning_rate: 0.00005
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 1500
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 1
  num_data_splits: 1
  eval_method: GRACE
  use_half_precision: false
DBLP:
  seed: 83521
  learning_rate: 0.00005
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 4
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.0
  tau: 0.7
  num_epochs: 1000
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 0
  num_data_splits: 1
  eval_method: GRACE
  use_half_precision: false
Reddit2:
  seed: 23344
  learning_rate: 0.000001
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 100
  num_data_splits: 128
  eval_method: DGI
  use_half_precision: false
Reddit:
  seed: 23344
  learning_rate: 0.000001
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 100
  num_data_splits: 128
  eval_method: DGI
  use_half_precision: false
ogbn_arxiv:
  seed: 23344
  learning_rate: 0.000001
  num_hidden: 1024
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 100
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 0.0001
  num_data_splits: 1
  eval_method: DGI
  use_half_precision: false
ogbn_products:
  seed: 23344
  learning_rate: 0.0001
  num_hidden: 512
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 2
  weight_decay: 0.00001
  max_edges_for_r: 2048
  kernel_lambda: 0
  num_data_splits: 1024
  eval_method: DGI
  use_half_precision: false
amazon_computers:
    seed: 39788
    learning_rate: 0.0001
    num_hidden: 512
    num_proj_hidden: 128
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    drop_edge_rate_1: 0.2
    drop_edge_rate_2: 0.4
    drop_feature_rate_1: 0.3
    drop_feature_rate_2: 0.4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
    max_edges_for_r: 2048
    kernel_lambda: 0.01
    num_data_splits: 1
    eval_method: GRACE
    use_half_precision: false
wiki_cs:
    seed: 39788
    learning_rate: 0.0001
    num_hidden: 512
    num_proj_hidden: 128
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    drop_edge_rate_1: 0.2
    drop_edge_rate_2: 0.4
    drop_feature_rate_1: 0.3
    drop_feature_rate_2: 0.4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
    max_edges_for_r: 2048
    kernel_lambda: 0.01
    num_data_splits: 1
    eval_method: GRACE
    use_half_precision: false
coauthor_physics:
    seed: 39788
    learning_rate: 0.0001
    num_hidden: 512
    num_proj_hidden: 128
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    drop_edge_rate_1: 0.2
    drop_edge_rate_2: 0.4
    drop_feature_rate_1: 0.3
    drop_feature_rate_2: 0.4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
    max_edges_for_r: 2048
    kernel_lambda: 0.01
    num_data_splits: 1
    eval_method: GRACE
    use_half_precision: false
coauthor_cs:
    seed: 39788
    learning_rate: 0.0001
    num_hidden: 512
    num_proj_hidden: 128
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    drop_edge_rate_1: 0.2
    drop_edge_rate_2: 0.4
    drop_feature_rate_1: 0.3
    drop_feature_rate_2: 0.4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
    max_edges_for_r: 2048
    kernel_lambda: 0.01
    num_data_splits: 1
    eval_method: GRACE
    use_half_precision: false
mag_240m:
  seed: 23344
  learning_rate: 0.00001
  num_hidden: 1024
  num_proj_hidden: 512
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  num_epochs: 2
  weight_decay: 0.00001
  max_edges_for_r: 4096
  kernel_lambda: 0
  num_data_splits: 8192
  eval_method: DGI
  use_half_precision: true
